birth_data = {'Louis Agassiz':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Louis_Agassiz&format=json',
'Maria Gaetana Agnesi':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Maria_Gaetana_Agnesi&format=json',
'Al-Battani':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Al-Battani&format=json',
'Abu Nasr Al-Farabi':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Abu_Nasr_Al-Farabi&format=json',
'Alhazen':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Alhazen&format=json',
'Jim Al-Khalili':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Jim_Al-Khalili&format=json',
'Muhammad ibn Musa al-Khwarizmi':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Muhammad_ibn_Musa_al-Khwarizmi&format=json',
'Mihailo Petrovic Alas':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Mihailo_Petrovic_Alas&format=json',
'Angel Alcala':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Angel_Alcala&format=json',
'Salim Ali':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Salim_Ali&format=json',
'Luis Alvarez':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Luis_Alvarez&format=json',
'Andre Marie Ampère':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Andre_Marie_Ampère&format=json',
'Anaximander':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Anaximander&format=json',
'Carl Anderson':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Carl_Anderson&format=json',
'Mary Anning':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Mary_Anning&format=json',
'Virginia Apgar':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Virginia_Apgar&format=json',
'Archimedes':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Archimedes&format=json',
'Agnes Arber':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Agnes_Arber&format=json',
'Aristarchus':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Aristarchus&format=json',
'Aristotle':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Aristotle&format=json',
'Svante Arrhenius':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Svante_Arrhenius&format=json',
'Oswald Avery':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Oswald_Avery&format=json',
'Amedeo Avogadro':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Amedeo_Avogadro&format=json',
'Avicenna':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Avicenna&format=json',
'Charles Babbage':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Charles_Babbage&format=json',
'Francis Bacon':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Francis_Bacon&format=json',
'Alexander Bain':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Alexander_Bain&format=json',
'John Logie Baird':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=John_Logie_Baird&format=json',
'Joseph Banks':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Joseph_Banks&format=json',
'Ramon Barba':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Ramon_Barba&format=json',
'John Bardeen':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=John_Bardeen&format=json',
'Charles Barkla':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Charles_Barkla&format=json',
'Ibn Battuta':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Ibn_Battuta&format=json',
'William Bayliss':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=William_Bayliss&format=json',
'George Beadle':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=George_Beadle&format=json',
'Arnold Orville Beckman':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Arnold_Orville_Beckman&format=json',
'Henri Becquerel':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Henri_Becquerel&format=json',
'Emil Adolf Behring':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Emil_Adolf_Behring&format=json',
'Alexander Graham Bell':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Alexander_Graham_Bell&format=json',
'Emile Berliner':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Emile_Berliner&format=json',
'Claude Bernard':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Claude_Bernard&format=json',
'Timothy John Berners-Lee':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Timothy_John_Berners-Lee&format=json',
'Daniel Bernoulli':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Daniel_Bernoulli&format=json',
'Jacob Berzelius':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Jacob_Berzelius&format=json',
'Henry Bessemer':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Henry_Bessemer&format=json',
'Hans Bethe':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Hans_Bethe&format=json',
'Homi Jehangir Bhabha':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Homi_Jehangir_Bhabha&format=json',
'Alfred Binet':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Alfred_Binet&format=json',
'Clarence Birdseye':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Clarence_Birdseye&format=json',
'Kristian Birkeland':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Kristian_Birkeland&format=json',
'Elizabeth Blackwell':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Elizabeth_Blackwell&format=json',
'Alfred Blalock':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Alfred_Blalock&format=json',
'Katharine Burr Blodgett':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Katharine_Burr_Blodgett&format=json',
'Franz Boas':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Franz_Boas&format=json',
'David Bohm':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=David_Bohm&format=json',
'Aage Bohr':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Aage_Bohr&format=json',
'Niels Bohr':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Niels_Bohr&format=json',
'Ludwig Boltzmann':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Ludwig_Boltzmann&format=json',
'Max Born':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Max_Born&format=json',
'Carl Bosch':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Carl_Bosch&format=json',
'Robert Bosch':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Robert_Bosch&format=json',
'Jagadish Chandra Bose':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Jagadish_Chandra_Bose&format=json',
'Satyendra Nath Bose':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Satyendra_Nath_Bose&format=json',
'Walther Wilhelm Georg Bothe':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Walther_Wilhelm_Georg_Bothe&format=json',
'Robert Boyle':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Robert_Boyle&format=json',
'Lawrence Bragg':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Lawrence_Bragg&format=json',
'Tycho Brahe':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Tycho_Brahe&format=json',
'Brahmagupta':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Brahmagupta&format=json',
'Hennig Brand':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Hennig_Brand&format=json',
'Georg Brandt':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Georg_Brandt&format=json',
'Wernher Von Braun':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Wernher_Von_Braun&format=json',
'J Harlen Bretz':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=J_Harlen_Bretz&format=json',
'Louis de Broglie':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Louis_de_Broglie&format=json',
'Alexander Brongniart':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Alexander_Brongniart&format=json',
'Robert Brown':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Robert_Brown&format=json',
'Michael E. Brown':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Michael_E._Brown&format=json',
'Lester R. Brown':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Lester_R._Brown&format=json',
'Eduard Buchner':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Eduard_Buchner&format=json',
'Linda Buck':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Linda_Buck&format=json',
'William Buckland':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=William_Buckland&format=json',
'Georges-Louis Leclerc, Comte de Buffon':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Georges-Louis_Leclerc,_Comte_de_Buffon&format=json',
'Robert Bunsen':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Robert_Bunsen&format=json',
'Luther Burbank':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Luther_Burbank&format=json',
'Jocelyn Bell Burnell':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Jocelyn_Bell_Burnell&format=json',
'Macfarlane Burnet':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Macfarlane_Burnet&format=json',
'Thomas Burnet':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Thomas_Burnet&format=json',
'Benjamin Cabrera':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Benjamin_Cabrera&format=json',
'Santiago Ramon y Cajal':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Santiago_Ramon_y_Cajal&format=json',
'Rachel Carson':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Rachel_Carson&format=json',
'George Washington Carver':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=George_Washington_Carver&format=json',
'Henry Cavendish':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Henry_Cavendish&format=json',
'Anders Celsius':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Anders_Celsius&format=json',
'James Chadwick':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=James_Chadwick&format=json',
'Subrahmanyan Chandrasekhar':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Subrahmanyan_Chandrasekhar&format=json',
'Erwin Chargaff':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Erwin_Chargaff&format=json',
'Noam Chomsky':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Noam_Chomsky&format=json',
'Steven Chu':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Steven_Chu&format=json',
'Leland Clark':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Leland_Clark&format=json',
'John Cockcroft':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=John_Cockcroft&format=json',
'Arthur Compton':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Arthur_Compton&format=json',
'Nicolaus Copernicus':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Nicolaus_Copernicus&format=json',
'Gerty Theresa Cori':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Gerty_Theresa_Cori&format=json',
'Charles-Augustin de Coulomb':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Charles-Augustin_de_Coulomb&format=json',
'Jacques Cousteau':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Jacques_Cousteau&format=json',
'Brian Cox':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Brian_Cox&format=json',
'Francis Crick':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Francis_Crick&format=json',
'James Croll':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=James_Croll&format=json',
'Nicholas Culpeper':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Nicholas_Culpeper&format=json',
'Marie Curie':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Marie_Curie&format=json',
'Pierre Curie':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Pierre_Curie&format=json',
'Georges Cuvier':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Georges_Cuvier&format=json',
'Adalbert Czerny':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Adalbert_Czerny&format=json',
'Gottlieb Daimler':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Gottlieb_Daimler&format=json',
'John Dalton':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=John_Dalton&format=json',
'James Dwight Dana':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=James_Dwight_Dana&format=json',
'Charles Darwin':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Charles_Darwin&format=json',
'Humphry Davy':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Humphry_Davy&format=json',
'Peter Debye':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Peter_Debye&format=json',
'Max Delbruck':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Max_Delbruck&format=json',
'Jean Andre Deluc':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Jean_Andre_Deluc&format=json',
'Democritus':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Democritus&format=json',
'René Descartes':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=René_Descartes&format=json',
'Rudolf Christian Karl Diesel':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Rudolf_Christian_Karl_Diesel&format=json',
'Diophantus':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Diophantus&format=json',
'Paul Dirac':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Paul_Dirac&format=json',
'Prokop Divis':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Prokop_Divis&format=json',
'Theodosius Dobzhansky':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Theodosius_Dobzhansky&format=json',
'Frank Drake':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Frank_Drake&format=json',
'K. Eric Drexler':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=K._Eric_Drexler&format=json',
'John Eccles':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=John_Eccles&format=json',
'Arthur Eddington':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Arthur_Eddington&format=json',
'Thomas Edison':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Thomas_Edison&format=json',
'Paul Ehrlich':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Paul_Ehrlich&format=json',
'Albert Einstein':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Albert_Einstein&format=json',
'Gertrude Elion':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Gertrude_Elion&format=json',
'Empedocles':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Empedocles&format=json',
'Eratosthenes':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Eratosthenes&format=json',
'Euclid':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Euclid&format=json',
'Leonhard Euler':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Leonhard_Euler&format=json',
'Michael Faraday':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Michael_Faraday&format=json',
'Pierre de Fermat':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Pierre_de_Fermat&format=json',
'Enrico Fermi':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Enrico_Fermi&format=json',
'Richard Feynman':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Richard_Feynman&format=json',
'Fibonacci – Leonardo of Pisa':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Fibonacci_–_Leonardo_of_Pisa&format=json',
'Emil Fischer':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Emil_Fischer&format=json',
'Ronald Fisher':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Ronald_Fisher&format=json',
'Alexander Fleming':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Alexander_Fleming&format=json',
'Ambrose Fleming':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Ambrose_Fleming&format=json',
'Howard Florey':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Howard_Florey&format=json',
'Henry Ford':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Henry_Ford&format=json',
'Lee De Forest':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Lee_De_Forest&format=json',
'Dian Fossey':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Dian_Fossey&format=json',
'Leon Foucault':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Leon_Foucault&format=json',
'Benjamin Franklin':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Benjamin_Franklin&format=json',
'Rosalind Franklin':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Rosalind_Franklin&format=json',
'Sigmund Freud':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Sigmund_Freud&format=json',
'Galen':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Galen&format=json',
'Galileo Galilei':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Galileo_Galilei&format=json',
'Francis Galton':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Francis_Galton&format=json',
'Luigi Galvani':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Luigi_Galvani&format=json',
'George Gamow':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=George_Gamow&format=json',
'Martin Gardner':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Martin_Gardner&format=json',
'Carl Friedrich Gauss':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Carl_Friedrich_Gauss&format=json',
'Murray Gell-Mann':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Murray_Gell-Mann&format=json',
'Sophie Germain':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Sophie_Germain&format=json',
'Willard Gibbs':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Willard_Gibbs&format=json',
'William Gilbert':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=William_Gilbert&format=json',
'Sheldon Lee Glashow':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Sheldon_Lee_Glashow&format=json',
'Robert Goddard':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Robert_Goddard&format=json',
'Maria Goeppert-Mayer':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Maria_Goeppert-Mayer&format=json',
'Thomas Gold':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Thomas_Gold&format=json',
'Jane Goodall':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Jane_Goodall&format=json',
'Stephen Jay Gould':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Stephen_Jay_Gould&format=json',
'Fritz Haber':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Fritz_Haber&format=json',
'Ernst Haeckel':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Ernst_Haeckel&format=json',
'Otto Hahn':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Otto_Hahn&format=json',
'Albrecht von Haller':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Albrecht_von_Haller&format=json',
'Edmund Halley':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Edmund_Halley&format=json',
'Thomas Harriot':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Thomas_Harriot&format=json',
'William Harvey':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=William_Harvey&format=json',
'Stephen Hawking':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Stephen_Hawking&format=json',
'Otto Haxel':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Otto_Haxel&format=json',
'Werner Heisenberg':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Werner_Heisenberg&format=json',
'Hermann von Helmholtz':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Hermann_von_Helmholtz&format=json',
'Jan Baptist von Helmont':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Jan_Baptist_von_Helmont&format=json',
'Joseph Henry':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Joseph_Henry&format=json',
'Caroline Herschel':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Caroline_Herschel&format=json',
'John Herschel':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=John_Herschel&format=json',
'William Herschel':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=William_Herschel&format=json',
'Gustav Ludwig Hertz':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Gustav_Ludwig_Hertz&format=json',
'Heinrich Hertz':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Heinrich_Hertz&format=json',
'Karl F. Herzfeld':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Karl_F._Herzfeld&format=json',
'George de Hevesy':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=George_de_Hevesy&format=json',
'Antony Hewish':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Antony_Hewish&format=json',
'David Hilbert':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=David_Hilbert&format=json',
'Maurice Hilleman':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Maurice_Hilleman&format=json',
'Hipparchus':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Hipparchus&format=json',
'Hippocrates':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Hippocrates&format=json',
'Shintaro Hirase':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Shintaro_Hirase&format=json',
'Dorothy Hodgkin':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Dorothy_Hodgkin&format=json',
'Robert Hooke':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Robert_Hooke&format=json',
'Frederick Gowland Hopkins':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Frederick_Gowland_Hopkins&format=json',
'William Hopkins':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=William_Hopkins&format=json',
'Grace Murray Hopper':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Grace_Murray_Hopper&format=json',
'Frank Hornby':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Frank_Hornby&format=json',
'Jack Horner':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Jack_Horner&format=json',
'Bernardo Houssay':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Bernardo_Houssay&format=json',
'Fred Hoyle':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Fred_Hoyle&format=json',
'Edwin Hubble':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Edwin_Hubble&format=json',
'Alexander von Humboldt':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Alexander_von_Humboldt&format=json',
'Zora Neale Hurston':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Zora_Neale_Hurston&format=json',
'James Hutton':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=James_Hutton&format=json',
'Christiaan Huygens':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Christiaan_Huygens&format=json',
'Hypatia':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Hypatia&format=json',
'Ernesto Illy':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Ernesto_Illy&format=json',
'Ernst Ising':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Ernst_Ising&format=json',
'Keisuke Ito':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Keisuke_Ito&format=json',
'Mae Carol Jemison':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Mae_Carol_Jemison&format=json',
'Edward Jenner':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Edward_Jenner&format=json',
'J. Hans D. Jensen':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=J._Hans_D._Jensen&format=json',
'Irene Joliot-Curie':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Irene_Joliot-Curie&format=json',
'James Prescott Joule':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=James_Prescott_Joule&format=json',
'Percy Lavon Julian':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Percy_Lavon_Julian&format=json',
'Michio Kaku':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Michio_Kaku&format=json',
'Heike Kamerlingh Onnes':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Heike_Kamerlingh_Onnes&format=json',
'Pyotr Kapitsa':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Pyotr_Kapitsa&format=json',
'Friedrich August Kekulé':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Friedrich_August_Kekulé&format=json',
'Frances Kelsey':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Frances_Kelsey&format=json',
'Pearl Kendrick':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Pearl_Kendrick&format=json',
'Johannes Kepler':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Johannes_Kepler&format=json',
'Abdul Qadeer Khan':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Abdul_Qadeer_Khan&format=json',
'Omar Khayyam':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Omar_Khayyam&format=json',
'Alfred Kinsey':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Alfred_Kinsey&format=json',
'Gustav Kirchoff':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Gustav_Kirchoff&format=json',
'Martin Klaproth':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Martin_Klaproth&format=json',
'Robert Koch':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Robert_Koch&format=json',
'Emil Kraepelin':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Emil_Kraepelin&format=json',
'Thomas Kuhn':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Thomas_Kuhn&format=json',
'Stephanie Kwolek':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Stephanie_Kwolek&format=json',
'Joseph-Louis Lagrange':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Joseph-Louis_Lagrange&format=json',
'Jean-Baptiste Lamarck':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Jean-Baptiste_Lamarck&format=json',
'Hedy Lamarr':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Hedy_Lamarr&format=json',
'Edwin Herbert Land':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Edwin_Herbert_Land&format=json',
'Karl Landsteiner':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Karl_Landsteiner&format=json',
'Pierre-Simon Laplace':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Pierre-Simon_Laplace&format=json',
'Max von Laue':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Max_von_Laue&format=json',
'Antoine Lavoisier':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Antoine_Lavoisier&format=json',
'Ernest Lawrence':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Ernest_Lawrence&format=json',
'Henrietta Leavitt':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Henrietta_Leavitt&format=json',
'Antonie van Leeuwenhoek':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Antonie_van_Leeuwenhoek&format=json',
'Inge Lehmann':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Inge_Lehmann&format=json',
'Gottfried Leibniz':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Gottfried_Leibniz&format=json',
'Georges Lemaître':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Georges_Lemaître&format=json',
'Leonardo da Vinci':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Leonardo_da_Vinci&format=json',
'Niccolo Leoniceno':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Niccolo_Leoniceno&format=json',
'Aldo Leopold':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Aldo_Leopold&format=json',
'Rita Levi-Montalcini':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Rita_Levi-Montalcini&format=json',
'Claude Levi-Strauss':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Claude_Levi-Strauss&format=json',
'Willard Frank Libby':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Willard_Frank_Libby&format=json',
'Justus von Liebig':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Justus_von_Liebig&format=json',
'Carolus Linnaeus':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Carolus_Linnaeus&format=json',
'Joseph Lister':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Joseph_Lister&format=json',
'John Locke':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=John_Locke&format=json',
'Hendrik Antoon Lorentz':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Hendrik_Antoon_Lorentz&format=json',
'Konrad Lorenz':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Konrad_Lorenz&format=json',
'Ada Lovelace':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Ada_Lovelace&format=json',
'Percival Lowell':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Percival_Lowell&format=json',
'Lucretius':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Lucretius&format=json',
'Charles Lyell':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Charles_Lyell&format=json',
'Trofim Lysenko':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Trofim_Lysenko&format=json',
'Ernst Mach':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Ernst_Mach&format=json',
'Marcello Malpighi':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Marcello_Malpighi&format=json',
'Jane Marcet':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Jane_Marcet&format=json',
'Guglielmo Marconi':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Guglielmo_Marconi&format=json',
'Lynn Margulis':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Lynn_Margulis&format=json',
'Matthew Maury':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Matthew_Maury&format=json',
'James Clerk Maxwell':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=James_Clerk_Maxwell&format=json',
'Ernst Mayr':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Ernst_Mayr&format=json',
'Barbara McClintock':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Barbara_McClintock&format=json',
'Lise Meitner':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Lise_Meitner&format=json',
'Gregor Mendel':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Gregor_Mendel&format=json',
'Dmitri Mendeleev':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Dmitri_Mendeleev&format=json',
'Franz Mesmer':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Franz_Mesmer&format=json',
'Antonio Meucci':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Antonio_Meucci&format=json',
'John Michell':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=John_Michell&format=json',
'Albert Abraham Michelson':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Albert_Abraham_Michelson&format=json',
'Thomas Midgeley Jr.':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Thomas_Midgeley_Jr.&format=json',
'Milutin Milanković':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Milutin_Milanković&format=json',
'Maria Mitchell':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Maria_Mitchell&format=json',
'Mario Molina':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Mario_Molina&format=json',
'Thomas Hunt Morgan':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Thomas_Hunt_Morgan&format=json',
'Samuel Morse':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Samuel_Morse&format=json',
'Henry Moseley':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Henry_Moseley&format=json',
'Ukichiro Nakaya':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Ukichiro_Nakaya&format=json',
'John Napier':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=John_Napier&format=json',
'Giulio Natta':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Giulio_Natta&format=json',
'John Needham':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=John_Needham&format=json',
'John von Neumann':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=John_von_Neumann&format=json',
'Thomas Newcomen':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Thomas_Newcomen&format=json',
'Isaac Newton':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Isaac_Newton&format=json',
'Charles Nicolle':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Charles_Nicolle&format=json',
'Florence Nightingale':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Florence_Nightingale&format=json',
'Tim Noakes':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Tim_Noakes&format=json',
'Alfred Nobel':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Alfred_Nobel&format=json',
'Emmy Noether':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Emmy_Noether&format=json',
'Christiane Nusslein-Volhard':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Christiane_Nusslein-Volhard&format=json',
'Bill Nye':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Bill_Nye&format=json',
'Hans Christian Oersted':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Hans_Christian_Oersted&format=json',
'Georg Ohm':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Georg_Ohm&format=json',
'J. Robert Oppenheimer':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=J._Robert_Oppenheimer&format=json',
'Wilhelm Ostwald':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Wilhelm_Ostwald&format=json',
'William Oughtred':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=William_Oughtred&format=json',
'Blaise Pascal':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Blaise_Pascal&format=json',
'Louis Pasteur':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Louis_Pasteur&format=json',
'Wolfgang Ernst Pauli':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Wolfgang_Ernst_Pauli&format=json',
'Linus Pauling':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Linus_Pauling&format=json',
'Randy Pausch':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Randy_Pausch&format=json',
'Ivan Pavlov':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Ivan_Pavlov&format=json',
'Cecilia Payne-Gaposchkin':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Cecilia_Payne-Gaposchkin&format=json',
'Wilder Penfield':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Wilder_Penfield&format=json',
'Marguerite Perey':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Marguerite_Perey&format=json',
'William Perkin':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=William_Perkin&format=json',
'John Philoponus':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=John_Philoponus&format=json',
'Jean Piaget':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Jean_Piaget&format=json',
'Philippe Pinel':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Philippe_Pinel&format=json',
'Max Planck':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Max_Planck&format=json',
'Pliny the Elder':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Pliny_the_Elder&format=json',
'Karl Popper':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Karl_Popper&format=json',
'Beatrix Potter':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Beatrix_Potter&format=json',
'Joseph Priestley':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Joseph_Priestley&format=json',
'Proclus':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Proclus&format=json',
'Claudius Ptolemy':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Claudius_Ptolemy&format=json',
'Pythagoras':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Pythagoras&format=json',
'Adolphe Quetelet':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Adolphe_Quetelet&format=json',
'Harriet Quimby':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Harriet_Quimby&format=json',
'Thabit ibn Qurra':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Thabit_ibn_Qurra&format=json',
'C. V. Raman':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=C._V._Raman&format=json',
'Srinivasa Ramanujan':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Srinivasa_Ramanujan&format=json',
'William Ramsay':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=William_Ramsay&format=json',
'John Ray':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=John_Ray&format=json',
'Prafulla Chandra Ray':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Prafulla_Chandra_Ray&format=json',
'Francesco Redi':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Francesco_Redi&format=json',
'Sally Ride':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Sally_Ride&format=json',
'Bernhard Riemann':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Bernhard_Riemann&format=json',
'Wilhelm Röntgen':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Wilhelm_Röntgen&format=json',
'Hermann Rorschach':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Hermann_Rorschach&format=json',
'Ronald Ross':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Ronald_Ross&format=json',
'Ibn Rushd':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Ibn_Rushd&format=json',
'Ernest Rutherford':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Ernest_Rutherford&format=json',
'Carl Sagan':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Carl_Sagan&format=json',
'Abdus Salam':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Abdus_Salam&format=json',
'Jonas Salk':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Jonas_Salk&format=json',
'Frederick Sanger':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Frederick_Sanger&format=json',
'Alberto Santos-Dumont':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Alberto_Santos-Dumont&format=json',
'Walter Schottky':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Walter_Schottky&format=json',
'Erwin Schrödinger':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Erwin_Schrödinger&format=json',
'Theodor Schwann':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Theodor_Schwann&format=json',
'Glenn Seaborg':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Glenn_Seaborg&format=json',
'Hans Selye':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Hans_Selye&format=json',
'Charles Sherrington':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Charles_Sherrington&format=json',
'Gene Shoemaker':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Gene_Shoemaker&format=json',
'Ernst Werner von Siemens':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Ernst_Werner_von_Siemens&format=json',
'George Gaylord Simpson':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=George_Gaylord_Simpson&format=json',
'B. F. Skinner':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=B._F._Skinner&format=json',
'William Smith':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=William_Smith&format=json',
'Frederick Soddy':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Frederick_Soddy&format=json',
'Mary Somerville':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Mary_Somerville&format=json',
'Arnold Sommerfeld':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Arnold_Sommerfeld&format=json',
'Hermann Staudinger':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Hermann_Staudinger&format=json',
'Nicolas Steno':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Nicolas_Steno&format=json',
'Nettie Stevens':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Nettie_Stevens&format=json',
'William John Swainson':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=William_John_Swainson&format=json',
'Leo Szilard':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Leo_Szilard&format=json',
'Niccolo Tartaglia':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Niccolo_Tartaglia&format=json',
'Edward Teller':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Edward_Teller&format=json',
'Nikola Tesla':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Nikola_Tesla&format=json',
'Thales of Miletus':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Thales_of_Miletus&format=json',
'Theon of Alexandria':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Theon_of_Alexandria&format=json',
'Benjamin Thompson':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Benjamin_Thompson&format=json',
'J. J. Thomson':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=J._J._Thomson&format=json',
'William Thomson':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=William_Thomson&format=json',
'Henry David Thoreau':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Henry_David_Thoreau&format=json',
'Kip S. Thorne':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Kip_S._Thorne&format=json',
'Clyde Tombaugh':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Clyde_Tombaugh&format=json',
'Susumu Tonegawa':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Susumu_Tonegawa&format=json',
'Evangelista Torricelli':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Evangelista_Torricelli&format=json',
'Charles Townes':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Charles_Townes&format=json',
'Youyou Tu':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Youyou_Tu&format=json',
'Alan Turing':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Alan_Turing&format=json',
'Neil deGrasse Tyson':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Neil_deGrasse_Tyson&format=json',
'Harold Urey':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Harold_Urey&format=json',
'Craig Venter':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Craig_Venter&format=json',
'Vladimir Vernadsky':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Vladimir_Vernadsky&format=json',
'Andreas Vesalius':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Andreas_Vesalius&format=json',
'Rudolf Virchow':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Rudolf_Virchow&format=json',
'Artturi Virtanen':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Artturi_Virtanen&format=json',
'Alessandro Volta':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Alessandro_Volta&format=json',
'Selman Waksman':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Selman_Waksman&format=json',
'George Wald':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=George_Wald&format=json',
'Alfred Russel Wallace':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Alfred_Russel_Wallace&format=json',
'John Wallis':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=John_Wallis&format=json',
'Ernest Walton':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Ernest_Walton&format=json',
'James Watson':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=James_Watson&format=json',
'James Watt':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=James_Watt&format=json',
'Alfred Wegener':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Alfred_Wegener&format=json',
'John Archibald Wheeler':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=John_Archibald_Wheeler&format=json',
'Maurice Wilkins':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Maurice_Wilkins&format=json',
'Thomas Willis':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Thomas_Willis&format=json',
'E. O. Wilson':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=E._O._Wilson&format=json',
'Sven Wingqvist':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Sven_Wingqvist&format=json',
'Sergei Winogradsky':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Sergei_Winogradsky&format=json',
'Carl Woese':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Carl_Woese&format=json',
'Friedrich Wöhler':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Friedrich_Wöhler&format=json',
'Wilbur and Orville Wright':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Wilbur_and_Orville_Wright&format=json',
'Wilhelm Wundt':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Wilhelm_Wundt&format=json',
'Chen-Ning Yang':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Chen-Ning_Yang&format=json',
'Ahmed Zewail':'http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&titles=Ahmed_Zewail&format=json'}